
CREATE TABLE `tweet` (
      `id` INT(11) NOT NULL AUTO_INCREMENT,
      `message` VARCHAR(255) NOT NULL,
      `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
